//  CITS2002 Project 1 2024
//  Student1:   23902644   Seoyoung Park
//  Student2:   23915299   Harper Chen
//  Platform:   Apple

// Compile this program with:
//      cc -std=c11 -Wall -Werror -o runml runml.c

// Please add comments and check if it runs without any errors before you push !!!


#include <stdio.h>	// prinf, fprintf, stderr, fopen
#include <stdlib.h>	// exit, EXIT_SUCCESS, atoi
#include <string.h>	// strlen
#include <ctype.h>	// islower
#include <stdbool.h>


bool checkFileExtension(const char* filePath) {
    size_t len = strlen(filePath);  // Get the length of the file path

    // Check if the file path is at least 3 characters long and ends with ".ml"
    if (len >= 3 && strcmp(filePath + len - 3, ".ml") == 0) {
        return true; // The file extension is .ml
    }
    
    return false; // The file extension is not .ml
}


int main(int argcount, char *argvalue[])
{
    if (argcount != 2) {  // Checks if exactly 1 argument is provided
        fprintf(stderr, "%s: program expected 1 argument, but instead received %i\n", argvalue[0], argcount-1);
        exit(EXIT_FAILURE);
    }

    if (checkFileExtension(argvalue[1])) {  // If the file is .ml
        FILE *file = fopen(argvalue[1], "r");
        if (file == NULL) {  // Check if the file was opened successfully
            fprintf(stderr, "%s: could not open file %s\n", argvalue[0], argvalue[1]);
            exit(EXIT_FAILURE);
        }
        // File opened successfully, do something with the file (e.g., read it)
        printf("File %s opened successfully!\n", argvalue[1]);  // GENERATED BY GPT SO I WILL ERASE THIS LINE LATER!! THIS IS JUST FOR CHECK IF THE FILE IS OPENED
        
        fclose(file);   // Close the file after usage
    } else {    // File is not .ml
        fprintf(stderr, "%s: program expected .ml file, but instead received %s\n", argvalue[0], argvalue[1]);
        exit(EXIT_FAILURE);
    }

    return 0;
}